"""
Django admin configuration for the algorithms app.

Customizes the admin panel to organize fields logically and add search/filter
capabilities. ExecutionLog is read-only since logs should only be created by
actual algorithm runs, not manually.
"""
from django.contrib import admin
from .models import Algorithm, ExecutionLog


@admin.register(Algorithm)
class AlgorithmAdmin(admin.ModelAdmin):
    """
    Admin interface for Algorithm model.

    Organizes fields into sections and adds filtering to make finding specific
    algorithms easier during testing and verification.
    """

    # Show key info in list view for quick overview
    list_display = ['name', 'category', 'time_complexity_average', 'space_complexity', 'is_stable', 'created_at']

    # Sidebar filters for browsing by category or stability
    list_filter = ['category', 'is_stable']

    # Search by name or description
    search_fields = ['name', 'description']

    # created_at is auto-set by Django
    readonly_fields = ['created_at']

    # Group related fields into logical sections
    fieldsets = [
        ('Basic Information', {
            'fields': ['name', 'category', 'description']
        }),
        ('Complexity Analysis', {
            # All Big-O complexity fields grouped together
            'fields': ['time_complexity_best', 'time_complexity_average',
                       'time_complexity_worst', 'space_complexity']
        }),
        ('Properties', {
            'fields': ['is_stable']
        }),
        ('Metadata', {
            'fields': ['created_at'],
            'classes': ['collapse']  # Collapsed by default - less important for daily use
        }),
    ]


@admin.register(ExecutionLog)
class ExecutionLogAdmin(admin.ModelAdmin):
    """
    Admin interface for viewing execution logs.

    Read-only design: Logs should only be created automatically when algorithms
    run. Manual creation would allow fake performance data that doesn't match reality.
    """

    # Show performance metrics in list view
    list_display = ['algorithm', 'input_size', 'execution_time_ms', 'comparisons', 'swaps', 'executed_at']

    # Filter by algorithm and date for finding specific runs
    list_filter = ['algorithm', 'executed_at']

    # Search across relationship to algorithm name
    search_fields = ['algorithm__name']

    # Timestamp reflects actual execution time
    readonly_fields = ['executed_at']

    # Date hierarchy for browsing logs by month/day
    date_hierarchy = 'executed_at'

    def has_add_permission(self, request):
        """
        Prevent manual creation of execution logs.

        Logs must be generated by actual algorithm runs to be meaningful.
        Manual creation would allow entering fake performance data.

        Returns False to hide the "Add" button in admin panel.
        """
        return False